#!/bin/bash
# GitHub plugin — install a git credential helper that fetches the PAT
# fresh per git op (so PAT rotation is automatic for git). Runs every boot.
#
# Reads from the standard ra contract:
#   GCP_PROJECT_ID
#   RA_PLUGIN_GITHUB_ENABLED
#   RA_SECRET_GITHUB_PAT_NAME  (gcp secret name, set by buildContainerEnv)
set -euo pipefail

GIT_HELPER_PATH="/usr/local/bin/git-credential-gcp-secret"

[ -r /run/ra/env ] && set -a && . /run/ra/env && set +a

[ "${RA_PLUGIN_GITHUB_ENABLED:-false}" = "true" ] || exit 0
: "${GCP_PROJECT_ID:?GCP_PROJECT_ID not set}"
: "${RA_SECRET_GITHUB_PAT_NAME:?RA_SECRET_GITHUB_PAT_NAME not set — install github plugin with the pat auth provider}"

# Always rewrite (handles rotation of the secret_name itself).
rm -f "${GIT_HELPER_PATH}"
cat > "${GIT_HELPER_PATH}" <<EOF
#!/bin/bash
# Auto-generated by github plugin. Emits GitHub PAT via git credential protocol.
while IFS= read -r line; do
    [[ -z "\$line" ]] && break
done
pat=\$(gcloud secrets versions access latest \\
    --secret='${RA_SECRET_GITHUB_PAT_NAME}' \\
    --project='${GCP_PROJECT_ID}' 2>/dev/null) || exit 0
echo "username=x-access-token"
echo "password=\${pat}"
EOF
chmod 0755 "${GIT_HELPER_PATH}"
git config --system credential.helper "${GIT_HELPER_PATH}"
echo "[github-credential-helper] installed ${GIT_HELPER_PATH} for secret ${RA_SECRET_GITHUB_PAT_NAME}"
